// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"ceshi/week4/app/internal/biz"
	"ceshi/week4/app/internal/data"
	"ceshi/week4/app/internal/server"
	"ceshi/week4/app/internal/service"
)

// Injectors from wire.go:

func InitService() (*server.GRPCServer, error) {
	userBaseRepo := data.NewUserRepo()
	userBaseUseCase := biz.NewUserBaseUseCase(userBaseRepo)
	levelInfoRepo := data.NewLevelInfoRepo()
	levelInfoUseCase := biz.NewLevelInfoUseCase(levelInfoRepo)
	userService := service.NewUserService(userBaseUseCase, levelInfoUseCase)
	grpcServer, err := server.NewGRPCServer(userService)
	if err != nil {
		return nil, err
	}
	return grpcServer, nil
}
